on: 
    push:
      branches:
        - master
name: 🚀 Deploy website on push
  
jobs:
    web-server-deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest


        steps:
        - name: Deploy using ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: |
              export NVM_DIR=~/.nvm
              source ~/.nvm/nvm.sh
              cd /var/www/vhosts/elvirainfotech.org/sirtifymebackend
              git pull origin master
              git status
              npm install --force
              pm2 restart 4